version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_v1
    hostname: metabase
    volumes:
      - metabase_data:/metabase-data
      - /dev/urandom:/dev/random:ro
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: "Prodam2024*NovoSGA!"
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -I http://localhost:3000/api/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_metabase_v1
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: "Prodam2024*NovoSGA!"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metanet1
    restart: always

volumes:
  metabase_data:
    driver: local
  postgres_data:
    driver: local

networks:
  metanet1:
    driver: bridge
